name: backend_as_service
description: A set of small examples showcasing each backend as a service dependency.
repository: https://github.com/iTEEECH/backend_as_service.git
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - apps/amplify_example
  - apps/appwrite_example
  - apps/firebase_example
  - apps/supabase_example

dev_dependencies:
  melos: 7.1.1

melos:
  command:
    version:
      # Generate commit links in package changelogs.
      linkToCommits: true
      # Only allow versioning to happen on main branch.
      # branch: main
      # Additionally build a changelog at the root of the workspace.
      workspaceChangelog: true

    bootstrap:
      runPubGetInParallel: false
      usePubspecOverrides: true

      environment:
        sdk: ^3.9.0

      dependencies:
        # https://pub.dev/packages/amplify_auth_cognito
        amplify_auth_cognito: 2.6.5
        # https://pub.dev/packages/amplify_flutter
        amplify_flutter: 2.6.5
        # https://pub.dev/packages/analyzer
        analyzer: 7.6.0
        # https://pub.dev/packages/appwrite
        appwrite: 19.0.0
        # https://pub.dev/packages/equatable
        equatable: 2.0.7
        # https://pub.dev/packages/firebase_auth
        firebase_auth: 5.5.1
        # https://pub.dev/packages/firebase_core
        firebase_core: 3.12.1
        # https://pub.dev/packages/flutter_hooks
        flutter_hooks: 0.21.3+1
        # https://pub.dev/packages/go_router
        go_router: 16.2.2
        # https://pub.dev/packages/hooks_riverpod
        hooks_riverpod: 3.0.0
        # https://pub.dev/packages/riverpod_annotation
        riverpod_annotation: 3.0.0
        # https://pub.dev/packages/supabase_flutter
        supabase_flutter: 2.9.0

      dev_dependencies:
        # https://pub.dev/packages/build_runner
        build_runner: 2.7.0
        # https://pub.dev/packages/flutter_lints
        flutter_lints: 6.0.0
        # https://pub.dev/packages/riverpod_generator
        riverpod_generator: 3.0.0

    clean:
      hooks:
        post: |
          melos exec -c 1 -- "flutter clean"

  scripts:
    analyze:
      description: Run `dart analyze` for all packages.
      run: dart analyze .
      exec:
        concurrency: 1

    generate:
      description: Run `dart run build_runner build --delete-conflicting-outputs` for all packages.
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        concurrency: 1
        failFast: true
      packageFilters:
        flutter: true
        dependsOn: build_runner

    pub:get:
      description: Run `flutter pub get` for all packages.
      run: flutter pub get

    test:unit:
      description: Run `flutter test` for all packages.
      run: flutter test
      exec:
        concurrency: 1
        failFast: true
      packageFilters:
        dirExists:
          - test

